Jenkinsfile_CNP
Jenkinsfile_parameterized
infrastructure/main.tf
infrastructure/state.tf
infrastructure/variables.tf

Creates CNP pipeline
Fixes # https://tools.hmcts.net/jira/browse/DIV-2118
Hasn't been tested.

DIV-2118: Create CNP pipeline

---

LICENSE
src/main/java/uk/gov/hmcts/reform/emclient/application/EvidenceManagementClientApplication.java
src/main/java/uk/gov/hmcts/reform/emclient/configuration/EvidenceManagementClientConfiguration.java
src/main/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientController.java
src/main/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalErrorAttributes.java
src/main/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/emclient/exception/BinaryUrlNotAvailableException.java
src/main/java/uk/gov/hmcts/reform/emclient/exception/TemporaryStoreFailureException.java
src/main/java/uk/gov/hmcts/reform/emclient/health/DefaultHttpEntityFactory.java
src/main/java/uk/gov/hmcts/reform/emclient/health/WebServiceHealthCheck.java
src/main/java/uk/gov/hmcts/reform/emclient/response/FileUploadResponse.java
src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadService.java
src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadServiceImpl.java
src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementUploadService.java
src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementUploadServiceImpl.java
src/main/java/uk/gov/hmcts/reform/emclient/service/UploadRequestBuilder.java
src/main/java/uk/gov/hmcts/reform/emclient/validation/constraint/EvidenceFile.java
src/main/java/uk/gov/hmcts/reform/emclient/validation/validator/EvidenceFileValidator.java
src/test/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientControllerTest.java
src/test/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalErrorAttributesTest.java
src/test/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalExceptionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/emclient/functional/HealthCheckFunctionalTest.java
src/test/java/uk/gov/hmcts/reform/emclient/health/DefaultHttpEntityFactoryTest.java
src/test/java/uk/gov/hmcts/reform/emclient/health/WebServiceHealthCheckTest.java
src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementUploadServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/emclient/service/UploadRequestBuilderTest.java
src/test/java/uk/gov/hmcts/reform/emclient/validation/validator/EvidenceFileValidatorTest.java

- Removed redundant code
- Optimised imports
- Updated License from 2017 -> 2018

Optimised imports, removed redundant code and updated LICENSE

---

Jenkinsfile

Changed the Jenkins file to take the correct jar file after gradle build
Fixes # [DIV-2265](https://tools.hmcts.net/jira/browse/DIV-2265)
This will be tested as part of the Jenkins pipeline

Changed the Jenkins file to take the correct jar file

---

Jenkinsfile
build.gradle

Add Pitest for PR

---

build.gradle

Increased the version to 2.2.0

Increased the verstion to 2.2.0

---

infrastructure/aat.tfvars
infrastructure/prod.tfvars

DIV-2308: Added AAT & Prod terraform var files

DIV-2308 Make EM work on all pipelines

---

build.gradle

This PR brings in the changes we did to fix the owasp issues in the cnp branch to the demo branch

Owaspfixes for demo branch

---

build.gradle

A new CVE was discovered in Spring Boot version from 1.5.0 to 1.5.9. Mitigation strategy is to update to Spring Boot version 1.5.10 
More information here 
Fixes # [DIV-2539](https://tools.hmcts.net/jira/browse/DIV-2539)
Confirmed that the version bump resolves the CVE

Updated the spring boot version to mitigate CVE-2018-1196

---

build.gradle

Changes are as follows:
Fix application insights logging issue: https://tools.hmcts.net/jira/browse/DIV-2611

Merge demo into master

---

dependency-check-suppressions.xml
infrastructure/main.tf
infrastructure/variables.tf

Preview environment expiry fixes
* Hardware:
* JDK:

Preview expiry fixes

---

build.gradle
dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDeleteServiceImpl.java
src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementUploadServiceImpl.java

Updates existing logs with userId retrieved from idam /details endpoints so its easier to search for logs when required.
https://tools.hmcts.net/jira/browse/DIV-3103
NOTE: I have added some dependency-check exclusions (copy and pasted from case-progression-service). These will be resolved when the migration to Spring Boot 2 occurs.

[PREVIEW] Update existing logs with userId details

---

infrastructure/main.tf
infrastructure/output.tf
infrastructure/variables.tf

[PREVIEW] cnp vault

---

infrastructure/main.tf

[PREVIEW] remove provider vault

---

infrastructure/main.tf
infrastructure/output.tf
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EMClientFileUploadTest.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/IDAMUtils.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/ResourceLoader.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/ServiceContextConfiguration.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/model/CreateUserRequest.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/model/UserCode.java
src/integrationTest/resources/application-aat.properties
src/integrationTest/resources/application-preview.properties
src/integrationTest/resources/application.properties

Required to fix integration tests for SIDAM. Should continue working with TIDAM.
These are temporary measures.
A common auth utils library for helping integration tests with IDAM will be implemented soon.

[PREVIEW] Fix integration tests for SIDAM

---

Dockerfile
Jenkinsfile_CNP
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EMClientFileUploadTest.java
src/integrationTest/resources/application-aat.properties
src/integrationTest/resources/application.properties
src/kubernetes/config.aat.yaml
src/kubernetes/deployment.template.yaml

enable building docker images on the pipeline

---

infrastructure/output.tf

Rename environment name

---

src/kubernetes/deployment.template.yaml

prepare for aks ingress

---

Dockerfile
Jenkinsfile_CNP
infrastructure/output.tf
infrastructure/prod.tfvars
src/integrationTest/resources/application-aat.properties
src/integrationTest/resources/application.properties
src/kubernetes/config.aat.yaml
src/kubernetes/deployment.template.yaml

Keep Demo Up To Date

---

infrastructure/main.tf

div-aat ASP has been split into two for resource issues:
div-1-aat and div-2-aat
Frontends and div-vs and div-fps will be part of 1.
All the remaining backends will be part of 2.

Move to shared ASP 2

---

src/main/java/uk/gov/hmcts/reform/emclient/application/EvidenceManagementClientApplication.java
src/main/java/uk/gov/hmcts/reform/emclient/config/HttpConnectionConfiguration.java
src/main/java/uk/gov/hmcts/reform/emclient/health/EvidenceManagementStoreAPI.java
src/main/java/uk/gov/hmcts/reform/emclient/health/ServiceAuthProviderHealthCheck.java
src/main/resources/application.properties
src/test/java/uk/gov/hmcts/reform/emclient/functional/HealthCheckFunctionalTest.java

To ensure /health responds in a reasonable time
Fixes #DIV-3885

DIV-3885 - set a separate timeout for health checks

---

Dockerfile
build.gradle
dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/reform/emclient/controller/RootController.java
src/test/java/uk/gov/hmcts/reform/emclient/controller/RootControllerTest.java

DIV-4409-added root controller with test

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
build.gradle
infrastructure/aat.tfvars
infrastructure/main.tf
infrastructure/output.tf
infrastructure/preview.tfvars
infrastructure/saat.tfvars
infrastructure/sandbox.tfvars
infrastructure/state.tf
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementFileDeleteIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementTestUtils.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/IDAMUtils.java
src/integrationTest/resources/application-aat.properties
src/integrationTest/resources/application-local.properties
src/integrationTest/resources/application-preview.properties
src/integrationTest/resources/application-saat.properties
src/integrationTest/resources/application.properties
src/kubernetes/config.aat.yaml

[DIV-4139](https://tools.hmcts.net/jira/browse/DIV-4319)
Mainly integration test refactors to help SIDAM and enable SAAT

Setup SAAT and SIDAM

---

dependency-check-suppressions.xml

Add CVE-2018-1258 suppression

---

build.gradle
src/main/java/uk/gov/hmcts/reform/emclient/config/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientController.java
src/main/resources/application.properties

Enable swagger

---

build.gradle

- OWASP upgraded to v5
Fixes # [DIV-5059](https://tools.hmcts.net/jira/browse/DIV-5059)

DIV-5059: OWASP upgrade

---

build.gradle
dependency-check-suppressions.xml

- Bumped dependencychecker to 5.1.1.
- Removed unnecessary suppressions
- Added a note around why current suppression is still required

Removed unnecessary suppressions

---

Jenkinsfile_CNP
charts/div-emca/values.aat.template.yaml

Make use of the identity resource we created in https://github.com/hmcts/cnp-flux-config/pull/460

DIV-5378: Enable AKS staging deployment

---

Jenkinsfile_CNP

Making sure Docker image is always built.

DIV-5378: update Jenkins_CNP

---

.gitignore
README.md
build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EMClientFileDownloadTest.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EMClientFileUploadTest.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementFileDeleteIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/IDAMUtils.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/IntegrationTest.java
src/integrationTest/resources/application-local.properties
src/integrationTest/resources/example-application-local.properties
src/main/resources/example-application-aat.yml

To better understand why master is failing with IDAM
Fixes #DIV-5378

DIV-5378 - improved integration tests logging

---

Jenkinsfile_CNP
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EMClientFileDownloadTest.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EMClientFileUploadTest.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementFileDeleteIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/IDAMUtils.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/IntegrationTest.java

Recent changes in #114 and #113  appear to require an explicit setting of the test_environment variable so that the correct application-${env}.properties file is picked up
Fixes #DIV-5378

DIV-5378 - Added Jenkins test_environment and refactored tests

---

src/main/resources/application.yml

DIV-5521 - removed dead config for Azure appinsights

---

infrastructure/aat.tfvars
infrastructure/prod.tfvars

Revert some required files from https://github.com/hmcts/div-evidence-management-client-api/pull/126
Fixes pipeline

Revert TF changes as pipeline still requires them

---

README.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat
src/main/java/uk/gov/hmcts/reform/emclient/idam/api/IdamApiClient.java
src/main/java/uk/gov/hmcts/reform/emclient/idam/services/UserService.java
src/main/java/uk/gov/hmcts/reform/emclient/validation/validator/EvidenceFileValidator.java

- Updated Jackson core & bind versions to remove vulnerability
- Updated Gradle wrapper version
- This allows us to enable IncrementalAnalysis for PMD which will speed up PMD checks: https://pmd.github.io/latest/pmd_userdocs_incremental_analysis.html#enabling-incremental-analysis
- Removed redundant blank lines and generally just formatted the code better

DIV-5991: Removed some code smell

---

build.gradle
dependency-check-suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EMClientFileUploadTest.java
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementFileDeleteIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/emclient/application/EvidenceManagementClientApplication.java
src/main/java/uk/gov/hmcts/reform/emclient/config/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientController.java
src/main/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/emclient/idam/models/UserDetails.java
src/main/java/uk/gov/hmcts/reform/emclient/response/FileUploadResponse.java
src/main/java/uk/gov/hmcts/reform/emclient/validation/constraint/EvidenceFile.java
src/test/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientControllerTest.java
src/test/java/uk/gov/hmcts/reform/emclient/controller/RootControllerTest.java
src/test/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalExceptionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/emclient/functional/BaseFunctionalTest.java
src/test/java/uk/gov/hmcts/reform/emclient/functional/EvidenceManagementDeleteFunctionalTest.java
src/test/java/uk/gov/hmcts/reform/emclient/functional/HealthCheckFunctionalTest.java
src/test/java/uk/gov/hmcts/reform/emclient/health/WebServiceHealthCheckTest.java
src/test/java/uk/gov/hmcts/reform/emclient/idam/UserServiceTest.java
src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDeleteServiceImplUTest.java
src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadServiceImplUTest.java
src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementUploadServiceImplUTest.java

- Updated minor dependency versions
- Removed unnecessary dependency check suppressions 
- Addressed some complaints identified by PMD
- Removed unnecessary blank lines etc

Updated minor dependency versions and removed unnecessary vuln suppressions

---

security.sh

applied recommended fixes on https://tools.hmcts.net/confluence/display/RQA/Integrate+with+Glue+for+ignoring+false+postivies

fix zap python compatibility

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementFileDeleteIntegrationTest.java

Upgrade tomcat

---

Jenkinsfile_CNP
build.gradle
dependency-check-suppressions.xml
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/RPET-242

RPET-242: Remove deprecated method installCharts

---

infrastructure/main.tf

Add provider "azurerm" to fix failing pipeline.

Add provider

---

build.gradle
charts/div-emca/Chart.yaml
charts/div-emca/requirements.yaml
charts/div-emca/values.aat.template.yaml
charts/div-emca/values.preview.template.yaml
charts/div-emca/values.yaml

Chart fixes

---

Dockerfile
build.gradle
lombok.config

Upgrade java 11

---

build.gradle

force snakeyaml to use 1.26, add local proxy config

---

README.md

Update README reference to Java 11

---

Jenkinsfile_CNP
README.md
build.gradle
src/contractTest/java/uk/gov/hmcts/reform/divorce/emclient/EmClientConsumerTest.java
src/contractTest/resources/application.yml

Yes
- [Y ] My code follows the style guidelines of this project
- [Y ] I have performed a self-review of my own code
- [ Y] I have commented my code, particularly in hard-to-understand areas
- [ Y] I have made corresponding changes to the documentation
- [Y ] My changes generate no new warnings
- [Y ] I have added tests that prove my fix is effective or that my feature works
- [ Y] New and existing unit tests pass locally with my changes
- [ Y] Any dependent changes have been merged and published in downstream modules

Ta 35 div em client consumer tests

---

Jenkinsfile_CNP

* Hardware:
* JDK:
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] Any dependent changes have been merged and published in downstream modules

updated the broker url location - Fixing master build

---

Jenkinsfile_CNP

adding missing library in jenkins library

---

dependency-check-suppressions.xml

Extending suppression date for longer to prevent build failures

Fixing build issues by extending suppression date further

---

build.gradle

Updating http client lib

---

build.gradle

Address bouncycastle issues

---

charts/div-emca/Chart.yaml
charts/div-emca/values.yaml
src/main/resources/bootstrap.yaml

fix logs not showing up in Azure

---

charts/div-emca/Chart.yaml

Upgrading to latest version of [chart-java (3.4.5)](https://github.com/hmcts/chart-java/releases/tag/v3.4.5)
https://tools.hmcts.net/jira/browse/RPET-921
platform operations upgrade

RPET-921 chart java bump

---

build.gradle

commonsIo                               : '2.7'

---

build.gradle
charts/div-emca/Chart.yaml

Upgrade tomcat and charts
DFR-518
- [ x] Bug fix (non-breaking change which fixes an issue)

DFR-518: Upgrade tomcat and charts

---

build.gradle
config/fortify-client.properties
dependency-check-suppressions.xml

Fortify Setup nightly build
DFR-467
- [ x] New feature (non-breaking change which adds functionality)

DFR-467: Fortify Setup

---

src/main/resources/application.yml

Remove no security for spring mgmt endpoints from config
DFR-552
- [x ] Bug fix (non-breaking change which fixes an issue)

DFR-552: Remove no security for spring mgmt endpoints

---

config/fortify-client.properties

DRF:736: updated fortify release id

DRF:736: updated fortify release id

---

charts/div-emca/Chart.yaml

bump java chart

---

dependency-check-suppressions.xml

Jackson suppression

---

build.gradle
charts/div-emca/Chart.yaml
charts/div-emca/values.yaml
dependency-check-suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementFileDeleteIntegrationTest.java

patch for dep check and fix test outcome

---

build.gradle
dependency-check-suppressions.xml

Bumping spring

---

charts/div-emca/Chart.yaml
dependency-check-suppressions.xml

Suppressing Tomcat

---

src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/IntegrationTest.java
src/integrationTest/resources/application.properties

Fix functional tests

---

build.gradle

Bumping snakeyaml

---

build.gradle

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X ] No
```

Updated snake.yaml version to 1.33

---

build.gradle
dependency-check-suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EmClientFileUploadTest.java
src/main/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalErrorAttributes.java
src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadServiceImplUTest.java
src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementUploadServiceImplUTest.java

Divorce: Modified serenity entry to 2.5.8

---

build.gradle
charts/div-emca/Chart.yaml

https://tools.hmcts.net/jira/browse/DFR-1808

DFR-1808 update charts

---

build.gradle
charts/div-emca/Chart.yaml
dependency-check-suppressions.xml

Fixes # dependencies issue
* Hardware:
* JDK:

Fix dependencies issue

---

src/contractTest/resources/application.yml

https://tools.hmcts.net/jira/browse/DFR-2641
Fix failing Spring startup due to missing Swagger bean configuration during contract test execution

Fix Swagger configuration

---

charts/div-emca/Chart.yaml
charts/div-emca/values.yaml
src/main/resources/application.yml
src/main/resources/bootstrap.yaml

Fix configuration for getting Azure secrets

Fix azure secrets configuration

---

infrastructure/state.tf

Update state.tf azurerm to allow non-prod deploy Fixes DTSPO-17720

Update state.tf azurerm to allow non-prod deploy

---

.github/renovate.json
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/DFR-3880
Disable renovate

DFR-3880: Disable renovate
